### ISSUE TITLE
IC2

### ISSUE THREAD

**Issue by JohnsBack** [Lythom/capsule#10]
Does this not work with IC2? I've tried OP and diamond with no luck. running 1.12.2

**Comment by Lythom** [comment]
Yes this is a known incompatibility, you can view all at https://github.com/Lythom/capsule/wiki/Known-incompatibilities. I once open a ticket about this (https://bt.industrial-craft.net/view.php?id=1957) but it looks heavily related to how IC2 is implemented and there is not much I can do about this right now.
