### ISSUE TITLE
[Suggestion] make one-use capsule copyable

### ISSUE THREAD

**Issue by Jecvay** [Lythom/capsule#11]
I want to put some beautiful building into one-use capsule and 
put these capsules to shop

player can buy one-use capsules

but now only the first buyer will get the building and then other players who buy the same capsule cannot get the building out.

**Comment by Lythom** [comment]
Hey ! Thanks submitting a suggestion.

If you have OP permissions, it can already be achieved by using some commands :
- `/capsule fromHeldCapsule myTemplateName` to create a template from any capsule you have in hand (https://github.com/Lythom/capsule/wiki/Commands#fromheldcapsule)
- `/capsule fromExistingReward myTemplateName` any number of times to get a copy of the template inside a new one-use capsule. (https://github.com/Lythom/capsule/wiki/Commands#fromexistingreward)

For survival, I currently have in my features backlog a "blueprint capsule", It would be like a rechargeable capsule that spawn a building and then can be reloaded with the buildling material to deploy again. It could contains several times the amount of materials to spawn the same building several times. With that logic in place (capsules holding their materials) I could easily add a recipe to craft a one-use capsule from a loaded blueprint. 
Can't give an ETA, I'll probably get back to the dev when forge 1.13 is stable to both improve 1.12 and update to 1.13.

Would it cover you need ?

**Comment by Jecvay** [comment]
/capsule fromExistingReward <templateName>
Can I run this by console ( such as shopgui click an item to run )
And give the product one use capsule to player who click this item?

or i need /capsule fromExistingReward <templateName> <playerName>

**Comment by Lythom** [comment]
Sorry for the delay, been testing to be sure and it appears you currently can't give a capsule from template usign a command block for example. 

`/capsule fromExistingReward <templateName> <playerName>` currently don't exists but I'm working on a fix for this, I'll let you know once it's released !

**Comment by Lythom** [comment]
Fixed by 0e667a471013d37bced3f414f5a78bb6b7b24d5f. Should be released in the coming days.

**Comment by Lythom** [comment]
Released : https://minecraft.curseforge.com/projects/capsule/files/2716860
