### ISSUE TITLE
Armor stand capsule found in dungeon loot does has no preview

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Lythom/capsule#111]
I found an armor capsule in a stronghold library chest. The capsule had no preview. When placed it contained a single armor stand. I suspect the mod doesn't know how to display entities.

Ideally the mod would display entities in the preview. If that isn't practical, build a display case around the armor stand in the structure so there is some kind of preview. I'd also rename the structure from armor to armor stand.

**Comment by Lythom** [comment]
Thanks for the feedback !
Indeed capsule can only render blocks and when entities such as armor stands or minecarts can't be rendered.
I don't expect it to change anytime soon, hope you'll still enjoy the capsule mod😄
