### ISSUE TITLE
SecurityCraft Imcompatability

### ISSUE THREAD

**Issue by Servaris1111** [Lythom/capsule#114]
I have found with securitycraft and capsules that capsules will steal itmes beyond restricted walls. rather then not capturing at all in detetction 0of anm excluded block. if this can be implemented it will allow much more compatability with security craft allowing players itmes to be safe. would be very cool to have this fix soon so that this mod can be easily implemented in my modpack and others to come Thank you.

**Comment by Lythom** [comment]
Oh, what version of caspule is that ?
Capsule has a specific integration with SecurityCraft for this specific use case (https://github.com/Lythom/capsule/blob/a1881ed43d9445ed48c31caa7710e2979359ed19/src/main/java/capsule/plugins/securitycraft/SecurityCraftOwnerCheck.java#L10), 

It should work fine up to 1.18.2 but wasn't tested further. Is the version of capsule used more recent than 1.18.2 ?

**Comment by Lythom** [comment]
Will be fixed in upcoming 1.20.4.
If you need the fix on a different version please let me know !
