### ISSUE TITLE
1.12.2 Serverside Crash

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lythom/capsule#12]
https://gist.github.com/P3rf3ctXZer0/76605380b2091f0c6717663356815ae4

**Comment by Lythom** [comment]
Fixed by a6e310261415acf460be44f5ce119601efe0dc3b.
Released in 3.2.92 at https://minecraft.curseforge.com/projects/capsule/files/2717238.

Thanks for your report 👍
