### ISSUE TITLE
Strange interactions with dye

### ISSUE THREAD

**Issue by Ghoul-Generator** [Lythom/capsule#13]
Mods:
Capsule-1.12.2-3.2.100
Ferdinand's+Flowers-1.12.x-1.10.4.1
JEI, Foamfix, TOP

Originally I spotted this issue with Ferdinand's but I've since come to realize this happens even with just capsule only and base minecraft dyes.

If you open a crafting table and place a stack of dye, sometimes, you'll get an output of another stack of dye, this new crafting recipe however is buggy on top of being unintended(?). When you craft the new dye, it only takes 1 item from the input stack. This is difficult to see if you only craft using a single item, but using an entire stack is the bug is obvious.

Dyes that this happens with:
minecraft:
cocoa beans -> Ink sac
Ferdinand's flowers:
Blue flower dye -> Light blue flower dye
Orange flower dye -> Dark red flower dye

**Comment by Lythom** [comment]
Thanks for the report!
I'll check this as soon as possible this week-end.

**Comment by Lythom** [comment]
Good catch! It is very unexpected, it's a side effect of the recipe that allows to clear a capsule.
Fixing and releasing, thanks for the help!

**Comment by Lythom** [comment]
Fix released in version v3.2.101.
https://www.curseforge.com/minecraft/mc-mods/capsule/files/all
