### ISSUE TITLE
Config Being Ignored

### ISSUE THREAD

**Issue by Boolyman** [Lythom/capsule#14]
I am trying stop new players of my modpack from having a ready made room capsule shoved into their inventory when they start a world.  I have tried everything from clearing the folder contents, to deleting the folder, to changing the path name in the config to an empty folder.  But it never fails... that capsule shows up on their hotbar when they load the world.

It seems to regenerate the folder section when the pack is first ran.  So it only shows up when someone downloads and installs the pack for the first time.  Once the pack is installed, if I change the config, it stays that, way and any worlds I start will not have the capsule in their hotbar.

**Comment by Lythom** [comment]
Hello ! 
If the folder does not already exists then it will be generated, it have to be already existing and empty. So you can create a new empty folder, for exemple "config/capsule/nostarters", then modify the capsule.cfg to have `S:starterTemplatesPath=config/capsule/nostarters` as the configured starter folder. The use of a new empty folder is to bypass updates that would keep the default starters folder that is already generated.
This is not intuitive so I'll make an update to have starters be disabled by empting the "S:starterTemplatesPath" value in config in the next update.
Thanks for reporting !

**Comment by Boolyman** [comment]
I understood how it is supposed to work, but it is not working like that.

**Comment by Lythom** [comment]
I just uploaded version 3.2.103 on curseforge which will properly disable the starter capsule when using an empty value for the "starterTemplatesPath" config.
Available at https://www.curseforge.com/minecraft/mc-mods/capsule/files.
