### ISSUE TITLE
[Submission] Tiny 3x3x3 huts, completely vanilla

### ISSUE THREAD

**Issue by Luminatron** [Lythom/capsule#16]

**Comment by Luminatron** [comment]
I'm new to this Github thing so idrk how to upload files...

**Comment by Lythom** [comment]
Received, thank you ! Will include in next release =)

**Comment by Lythom** [comment]
Added as random starters in latest version 3.3.5 at https://www.curseforge.com/minecraft/mc-mods/capsule/files. Thanks for the contribution :)
