### ISSUE TITLE
[Submission]

### ISSUE THREAD

**Issue by KamSolastor** [Lythom/capsule#17]
Here are a four loot rewards that could be added. One is a small house (I believe it's close to 7x7x7) that could be either used as a reward, or an alternative starter house  (though tbh I really do like the original one you included, especially the second floor!). The other three were a odd thought I had - a medium, large, and crazy huge (for common, uncommon, and rare loot folders) - They contain a 3x3x3, 5x5x5, and 9x9x9 cube containing most of the vanilla ores and resources to reward a lucky player on finding them - coal, iron, redstone, lapis, gold, glowstone, nether quartz, diamond, emerald. The 3x3x3 cube has 3 of each, the 5x5x5 cube has around 16 of each, with more weight to iron and coal, and less to diamond, emerald, gold, and quartz. The 9x9x9 has 9 of each. Don't know if you might feel that's too cheaty, but I felt it might be a nice reward for players to stumble upon. 

[rewards.zip](https://github.com/Lythom/capsule/files/3608082/rewards.zip)

**Comment by KamSolastor** [comment]
Also, let me know if you get the .zip files I uploaded into GitHub here, if not I'll upload them to mediafire or another site if you'd like.

**Comment by Lythom** [comment]
Received, thank you ! Will check them out and include in next release =)
I'll see but I don't think it's "cheaty" (you trade mining for exploration to get them). I'll add a warn notice for modpack makers though so that they disable them if it would break their progression if any.

**Comment by Lythom** [comment]
Submission included as loots (blueprints) in latest version 3.3.5 at https://www.curseforge.com/minecraft/mc-mods/capsule/files. Might break some progressions indeed, I trust modpackers to remove the loots if it doesn't fit their vision.
