### ISSUE TITLE
[Submission]

### ISSUE THREAD

**Issue by KamSolastor** [Lythom/capsule#18]
Here's a few more loot capsule plans, all farms. The one 'large' and two 'enclosed' farms are in a enclosed building, allowing them to be a great addition to a players base. The others are open on two sides, allowing for further modification if players want, or allowing them to add it to any existing farm or their current base, or further modify it if they want. 
[Farm Plot Capsules.zip](https://github.com/Lythom/capsule/files/3612048/Farm.Plot.Capsules.zip)

**Comment by Lythom** [comment]
Received, thank you ! Will check them out and include in next release =)

**Comment by Lythom** [comment]
Submission included as loots (blueprints) in latest version 3.3.5 at https://www.curseforge.com/minecraft/mc-mods/capsule/files. I hope players will use the farm blueprints :)
