### ISSUE TITLE
[Feature Request] Randomized Starters

### ISSUE THREAD

**Issue by happybandit360** [Lythom/capsule#19]
Would it be possible to get an option to give a player one random capsule from the starters folder instead of everything in there?

**Comment by Lythom** [comment]
Seems to be a small evolution and that it would add value to the mod, putting the feature to the backlog, will implement it in next update (but not sure yet when I'll take that time).
Thanks for your contribution !

**Comment by Lythom** [comment]
Option available in latest version 3.3.5 at https://www.curseforge.com/minecraft/mc-mods/capsule/files. Thanks for the suggestion :)
