### ISSUE TITLE
Server crashes when adding capsule mod.

### ISSUE THREAD

**Issue by LennartCockx** [Lythom/capsule#20]
I recently started playing a new modpack based on enigmatica 2, with some extra mods added. 
I wanted to add the capsule mod too (I used it to store builds from previous modpacks), but the game crashes as soon as I try to load a map (the game boots to the main menu without issues)

I'm not certain if this is caused by the capsule mod or another mod that makes changes which cause a conflict. Removing the capsule mod resolved the issue. 

Full crashlog:
https://gist.github.com/LennartCockx/96191b9e6f01d18f378db98f1adad46d

**Comment by Lythom** [comment]
Thanks for the report, it looks related to the starter capsule that was recently added, will be looking into this soon.

**Comment by Lythom** [comment]
Not as soon as I thought but well, the fix is available from version 3.3.5 at https://www.curseforge.com/minecraft/mc-mods/capsule/files.

**Comment by LennartCockx** [comment]
Awesome, thanks!
