### ISSUE TITLE
[Enhancement] Some way to make duplicate structure capsules in a balance-friendly way.

### ISSUE THREAD

**Issue by Corvus20** [Lythom/capsule#39]
I had this idea a while back when I was playing on a modded server with some friends, I wondered if I could make money (it was a competitive server) by selling them prefabricated machines, shelters, etc. If there was a machine that would take a filled capsule on one side as a template, and would take account of all the blocks, it could accept the items needed to make a copy of it in another capsule. Allowing you to make multiple copies of structures assuming you have the supplies you would need to construct them. It just helps with building similar structures repeatedly.

**Comment by Lythom** [comment]
Yes, that's basically what blueprint capsules does, see https://github.com/Lythom/capsule/wiki#blueprints
Have fun !
