### ISSUE TITLE
Corail Tombstone dupe bug

### ISSUE THREAD

**Issue by Nachodde** [Lythom/capsule#45]
Using any capsule to encapsulate a gravestone from the Corail Tombstone mod, the capsule takes a copy of the gravestone and leaves a copy behind. the copy in the capsule can be deployed to have 2 identical fully functioning gravestones.

**Comment by Lythom** [comment]
Thanks for reporting ! 
Can you specify the versions of Capsule and Corail Tombstone ?
A quick fix is to add the Corail Tombstone gravestone in the "ignored" part of the capsule configuration file. I'll check that and make it ignored by default if I can't find a workaround.

**Comment by Lythom** [comment]
Fixed with https://github.com/Lythom/capsule/issues/46
To be released in the upcoming versions of capsule
