### ISSUE TITLE
Fix starter base  blueprint recipe on 1.12.2, ver. 3.4.58

### ISSUE THREAD

**Issue by Lythom** [Lythom/capsule#49]
remove the whole recipe ?

**Comment by YoYoK3nny** [comment]
It can be fixed by changing the structureName entry to `assets/capsule/starters/starter_traveller's_base` instead of `assets/capsule/starters/traveller's_base`. (_Tested working after this change_)

Handy to keep it in as a quick template for a movable base, before moving on to building our own.
