### ISSUE TITLE
【proposal】New tool, Son Gohan's capsule watch

### ISSUE THREAD

**Issue by GalaxyZEROX** [Lythom/capsule#52]
Can I add Son Gohan's capsule watch in Dragon Ball Z? The kind that can store/put on a whole set of armor in an instant?1.12.2

**Comment by Lythom** [comment]
Oh sounds great. Do you have any link to a video that showcases the Son Gohan's capsule watch ?
This will not be a priority since dispensers can already manipulate armors in vanilla, but I'll consider the idea !

**Comment by Lythom** [comment]
Removed from feature list : full armor equipment is handled by other mods already + 1.12.2 is not maintained anymore.
Feel free to renew the proposal for a more recent version of minecraft (1.18) and specify how it would be unique from the vanilla feature.
