### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Lythom/capsule#53]
`Forge v36.2.2`
`Minecraft v1.16.5`
`Capsule v5.0.73`

I randomly got a server crash while exploring. A capsule was not used at the time of the crash.
[Crash Report](https://gist.github.com/WenXin20/4755d3404783314a391d5fdbb45d4506#file-capusle_server_crash-txt-L7131)

**Comment by Lythom** [comment]
Hi !
I have a proper way to fix this so I'll be fixing that shortly.
To give some insight, it looks like the crash comes from a function that is usually only called client-side but fails when called server-side. This call is never done usually but inventorypets looks to do it anyway. That said the function does exists on server and is not forbidden to be called so I'll fix the capsule code to account for this use case.
Thanks for reporting! It helps the mod getting better 👍.

**Comment by WenXin20** [comment]
Thanks! I've had it happen multiple times since this report. I was wondering if Inventory Pets were somehow involved.

**Comment by Lythom** [comment]
Inventory pets is involved because it calls the Item.getName() method on the server, which vanilla and most mods don't do. It still should work.

**Comment by Lythom** [comment]
Fixed in 5.0.75
Should be up soon at https://www.curseforge.com/minecraft/mc-mods/capsule/files
