### ISSUE TITLE
Crash while renaming capsule

### ISSUE THREAD

**Issue by Herbadableh** [Lythom/capsule#58]
I really just don't know.
1.12.2 version, mod version 3.3.11
MC Eternal pack
https://pastebin.com/2Vd3hs0F

**Comment by Lythom** [comment]
Thanks for reporting ! I'll try the reproduce the issue and see what's going on.

**Comment by Herbadableh** [comment]
ok so for further information to reproduce it, it only seems to happen when the capsule is currently deployed.

**Comment by Lythom** [comment]
I'm unfortunatly not able to maintain 1.12 version anymore, so the bug will have to stay :(
