### ISSUE TITLE
Is there some way you can increase the Performance of this mod?

### ISSUE THREAD

**Issue by Z3r0ut** [Lythom/capsule#66]
Cause when i set in the config that they accept more upgrades, the game doesnt load anymore. I mean, when i use a capsule higher than normal max (31x31x31) the area disappears always almost instandly like it should, but when i try to place it again the preview never shows up and the server doesnt load anymore, i have "waiting for server" then.

**Comment by Lythom** [comment]
I've been away for some time, sorry for late answer !
Capsules are indeed not designed to be "too big", it used to have a hard limit that I removed for people to be able to experiment by thereself beyond the default limits (so well done there :D). 
I need a few more information to fully answer :    
- what version of capsule have you been experimenting this behaviour with ?
- is there a log message on the server associated with the server hang out ?
- How big was the area you tried to capture and display ?

I don't plan to improve performances better than what I've already done, but the server is not supposed to crash or the capsule to become unusable, in latests versions there is a fallback in case of the preview being too big to be displayed.

Also keep in mind that the "machine power" required to handle a full content grow VERY sharply depending on the capsule size :    
- 31x31x31 is 29 791 blocks
- 39x39x39 is 59 319 block (+8 in dimensions give twice the content size, so performances divided by 2, and 31x31x31 is already big)
- 45x45x45 is 91 125 blocks (+13 in dimensions give three times the content size, so performances divied by 3)
