### ISSUE TITLE
Blueprints not responding in any way when trying to refill them.

### ISSUE THREAD

**Issue by PlasmaticPi** [Lythom/capsule#79]
I'm on the 1.18.2 version of minecraft using the Plexiglass Mountain FTB modpack. I've made a blueprint from a house I want to make copies of for my village, but no matter what I do it won't fill from my inventory or a linked chest's inventory despite having all the blocks, and never shows the list of blocks needed in chat like it is supposed to.

**Comment by oliverrook** [comment]
Can confirm this

**Comment by Lythom** [comment]
Thanks for reporting, the issue was identified a the fix will be deployed in next release!

**Comment by Lythom** [comment]
Ok I lost track of my fixes T_T
The fix was already released and it's fixed in capsule 5.0.94+ (https://www.curseforge.com/minecraft/mc-mods/capsule/files/3915875)

**Comment by Lythom** [comment]
Fixed in version 1.18.2-6.0.95 (currently uploading). Available at https://www.curseforge.com/minecraft/mc-mods/capsule/files
