### ISSUE TITLE
[Suggestion] A smoke effect when deploying/recovering capsules would be awesome!

### ISSUE THREAD

**Issue by LennartCockx** [Lythom/capsule#9]
This mod is just fantastic, I love using it to bring small utilities when exploring or bringing entire bases with me. If there is only one thing I would love to see added, then it would be some kind of smoke effect when deploying capsules. It could be something very simple, but currently it can be somewhat underwhelming when you deploy a 5x5x5 with all kinds of machines inside.

Thank you and keep up the great work!

**Comment by LennartCockx** [comment]
Thanks for considering my suggestion!
I'm learning the basics of minecraft modding myself at the moment, so perhaps if I figure out something I'll do a pull request. Still a lot to learn though.

Looking forward to it!

**Comment by Lythom** [comment]
The project architecture is straightforward so it might be a good 1st time contribution ! If you know either Jenkis or Docker you'll find the information you need in Jenkinsfile or Dockerfile to build the jar for a quick test. Other than that, the project is a typical forge mod, so to setup a full dev environement you can start at step 4 of https://mcforge.readthedocs.io/en/latest/gettingstarted/#from-zero-to-modding.

**Comment by Lythom** [comment]
Fixed by 969742b98ee6d1d16e42b846448de61c43de9f61. To be released in the coming days.

**Comment by Lythom** [comment]
New version of capsule released : https://minecraft.curseforge.com/projects/capsule/files/2716860
